[package]
name = "rmf_site_map_server"
version = "0.4.1"
authors = ["Luca Della Vedova <lucadv@intrinsic.ai>"]
edition = "2021"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
rmf_site_format = "0.0.2"

[[bin]]
name = "site_map_server"
path = "src/main.rs"

[dependencies.rclrs]
git = "https://github.com/ros2-rust/ros2_rust"
rev = "d27a8cb9ccea23446c0e37fe56ba2623ade892af"

[dependencies.ros-env]
version = "0.2"
